version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: pdf_processor
      POSTGRES_USER: mike
      POSTGRES_PASSWORD: L54he&#XhM4n

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8080 djangoProject.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: